version: "3.9"

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    volumes:
      - ./backend/mysql/.data:/var/lib/mysql
      - ./backend/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  wordpress:
    depends_on:
      - mysql
    image: wordpress:6.6.2-php8.1-apache
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: demo
      WORDPRESS_DB_USER: demo
      WORDPRESS_DB_PASSWORD: demo

  astro:
    build:
      context: "./frontend"
    ports:
      - "4321:4321"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./frontend/astro:/app
    stdin_open: true
    tty: true